"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Talents = [
    {
        Id: 1,
        EmployeeId: 'K11312',
        Name: 'khalil, MOhamed',
        Manager: 'Jones,Brian',
        Function: 'Finance',
        AreaHead: 'Khalil, Salma',
        Division: 'DP&BS',
        //Division: undefined,
        Unit: 'Enviromental',
        Stream: 'Environmental Central',
        Location: 'Environmental Central - Corby Borough Council',
        BusinessRisk: 'High',
        FlightRisk: 'High',
        Performance: '2',
        Potential: 'B',
        Grade: 'L2',
        Movement: 'Soon',
        Requirements_01_category: 'Technical Training',
        Requirements_01_subcategory: 'Option 2',
        Requirements_02_category: 'Technical Training',
        Requirements_02_subcategory: 'Option 3',
        Notes: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sed fermentum ex, sit amet congue eros. Ut cursus mattis feugiat. Aenean tristique ante in urna lobortis, sit amet luctus nulla dapibus. Etiam sodales, odio et faucibus placerat, libero ligula lobortis augue, quis malesuada sem enim in erat. Donec eu lorem sit amet nulla congue porta ut vitae dui. Fusce dignissim ullamcorper lorem eu sagittis. Ut mollis purus vel nibh mollis dignissim.'
    },
    {
        Id: 2,
        EmployeeId: 'K11312',
        Name: 'khalil, MOhamed',
        Manager: 'Jones,Brian',
        AreaHead: 'Khalil, Salma',
        Function: 'Procurement',
        Division: 'DP&BS',
        Unit: 'Enviromental',
        Stream: 'Environmental Central',
        Location: 'Environmental Central - Cheshire West & Chester',
        BusinessRisk: 'High',
        FlightRisk: 'High',
        Performance: '5',
        Potential: 'A',
        Grade: "M3",
        Movement: 'Soon',
        Requirements_01_category: 'Technical Training',
        Requirements_01_subcategory: 'Option 2',
        Requirements_02_category: 'Technical Training',
        Requirements_02_subcategory: 'Option 3',
        Notes: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sed fermentum ex, sit amet congue eros. Ut cursus mattis feugiat. Aenean tristique ante in urna lobortis, sit amet luctus nulla dapibus. Etiam sodales, odio et faucibus placerat, libero ligula lobortis augue, quis malesuada sem enim in erat. Donec eu lorem sit amet nulla congue porta ut vitae dui. Fusce dignissim ullamcorper lorem eu sagittis. Ut mollis purus vel nibh mollis dignissim.'
    },
    {
        Id: 3,
        EmployeeId: 'K11312',
        Name: 'khalil, MOhamed',
        Manager: 'Jones,Brian',
        AreaHead: 'Khalil, Salma',
        Division: 'DP&BS',
        Function: 'Procurement',
        Unit: 'Enviromental',
        Stream: 'Environmental Central',
        Location: 'Environmental Central - Cheshire West & Chester',
        BusinessRisk: 'High',
        FlightRisk: 'High',
        Performance: '5',
        Potential: 'A',
        Movement: 'Soon',
        Requirements_01_category: 'Technical Training',
        Requirements_01_subcategory: 'Option 2',
        Requirements_02_category: 'Technical Training',
        Requirements_02_subcategory: 'Option 3',
        Notes: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sed fermentum ex, sit amet congue eros. Ut cursus mattis feugiat. Aenean tristique ante in urna lobortis, sit amet luctus nulla dapibus. Etiam sodales, odio et faucibus placerat, libero ligula lobortis augue, quis malesuada sem enim in erat. Donec eu lorem sit amet nulla congue porta ut vitae dui. Fusce dignissim ullamcorper lorem eu sagittis. Ut mollis purus vel nibh mollis dignissim.'
    },
    {
        Id: 4,
        EmployeeId: 'K11312',
        Name: 'khalil, MOhamed',
        Manager: 'Jones,Brian',
        AreaHead: 'Khalil, Salma',
        Division: 'DP&BS',
        Unit: 'Enviromental',
        Function: 'Finance',
        Stream: 'Environmental Central',
        Location: 'Environmental Central - Cheshire West & Chester',
        BusinessRisk: 'High',
        FlightRisk: 'High',
        Performance: '4',
        Potential: 'A',
        Movement: 'Soon',
        Requirements_01_category: 'Technical Training',
        Requirements_01_subcategory: 'Option 2',
        Requirements_02_category: 'Technical Training',
        Requirements_02_subcategory: 'Option 3',
        Notes: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras sed fermentum ex, sit amet congue eros. Ut cursus mattis feugiat. Aenean tristique ante in urna lobortis, sit amet luctus nulla dapibus. Etiam sodales, odio et faucibus placerat, libero ligula lobortis augue, quis malesuada sem enim in erat. Donec eu lorem sit amet nulla congue porta ut vitae dui. Fusce dignissim ullamcorper lorem eu sagittis. Ut mollis purus vel nibh mollis dignissim.'
    }
];
exports.default = Talents;
//# sourceMappingURL=Talents.js.map